#  Beanspeak
#
#  Copyright (c) 2016 Phalcon Team (https://www.phalconphp.com)
#
#  This source file is subject to the New BSD License that is bundled
#  with this package in the file LICENSE.txt.
#
#  If you did not receive a copy of the license and are unable to
#  obtain it through the world-wide-web, please send an email
#  to license@phalconphp.com so we can send you a copy immediately.
#
#  Authors: Serghei Iakovlev <serghei@phalconphp.com>

language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  include:
    - php: 7.0
      env: ZEND_BACKEND="--backend=ZendEngine3"
    - php: 7.1
      env: ZEND_BACKEND="--backend=ZendEngine3"

sudo: required
dist: trusty

git:
  depth: 1

cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - .temp
    - $HOME/.ccache
    - $HOME/.composer/cache

env:
  global:
    - TEST_BT_HOST="127.0.0.1"
    - TEST_BT_PORT="11300"
    - ZEND_DONT_UNLOAD_MODULES=1
    - CC="ccache gcc"

before_install:
  - export PATH=$PATH:~/bin;
  - phpenv config-rm xdebug.ini || true
  - composer self-update -q
  - travis_retry composer --prefer-source install
  - bash tests/_ci/install_zephir.sh
  - bash tests/_ci/install_beanstalkd.sh
  - '( zephir fullclean && zephir generate $ZEND_BACKEND )'

before_script:
  - (export PRE_PHP_INCLUDES=`php-config --includes`; cd ext/; for file in `find kernel -name "*.h"`; do $CC "$file" -I. $PRE_PHP_INCLUDES -o "$file.ghc"; done)
  - (cd ext; export CFLAGS="-g3 -O1 -std=gnu90 -Wall -DZEPHIR_RELEASE=1"; phpize &> /dev/null && ./configure --silent --enable-beanspeak &> /dev/null && make --silent -j4 &> /dev/null && make --silent install)
  - phpenv config-add tests/_ci/beanspeak.ini
  - php --ri beanspeak
  - ulimit -c unlimited -S || true
  - echo "/tmp/beanspeak/core-%e.%p" | sudo tee /proc/sys/kernel/core_pattern &> /dev/null

script:
  - vendor/bin/codecept run -v

after_failure:
  - bash tests/_ci/backtrace.sh

addons:
  apt:
    packages:
      - gdb
      - re2c

notifications:
  email:
    recipients:
      - build@phalconphp.com
    on_success: change
    on_failure: always
