language: php

branches:
  except:
    - docs

sudo: required
dist: trusty

env:
  global:
    - TEST_BT_HOST="127.0.0.1"
    - TEST_BT_PORT="11300"
  matrix:
    - PHP_VERSION="5.4"
    - PHP_VERSION="5.5"
    - PHP_VERSION="5.6"
    - PHP_VERSION="7"

cache:
  - apt

before_install:
  - travis_retry composer self-update
  - sudo service docker stop

install:
  # Install Docker
  - sudo apt-get update -qq
  - sudo apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y --force-yes docker-engine
  - sudo service docker restart
  # Install Zephir
  - docker pull phalconphp/zephir:$PHP_VERSION
  - sudo cp tests/_ci/zephir.sh /usr/local/bin/zephir && sudo chmod +x /usr/local/bin/zephir
  # Install PHP
  - docker pull phalconphp/php:$PHP_VERSION
  - sudo cp tests/_ci/php.sh /usr/local/bin/php && sudo chmod +x /usr/local/bin/php
  # Install Beanstalk
  - bash tests/_ci/install_beanstalkd.sh

before_script:
  # Build extension
  - '[[ "$PHP_VERSION" == "7" ]] || zephir $PHP_VERSION build'
  - '[[ "$PHP_VERSION" != "7" ]] || zephir $PHP_VERSION build --ZendEngine3'

  #- echo "extension=${TRAVIS_BUILD_DIR}/ext/modules/beanspeak.so" | tee tests/_ci/beanspeak.ini
  #- phpenv config-add tests/_ci/beanspeak.ini
  - stty cols 160

script:
  - zephir $PHP_VERSION version
  - php $PHP_VERSION -v
  - ls -l "${TRAVIS_BUILD_DIR}/ext/modules"

  #- php --ri beanspeak
