language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

sudo: required
dist: precise
group: edge

env:
  global:
    - TEST_BT_HOST="127.0.0.1"
    - TEST_BT_PORT="11300"

cache:
  - apt

before_install:
  - export PATH=$PATH:~/bin;
  - travis_retry composer self-update
  - travis_retry composer require phalcon/zephir:dev-master
  - bash tests/_ci/install_zephir.sh
  - bash tests/_ci/install_beanstalkd.sh
  - '[[ "$TRAVIS_PHP_VERSION" == "7" ]] || zephir generate'
  - '[[ "$TRAVIS_PHP_VERSION" != "7" ]] || zephir generate --ZendEngine3'

before_script:
  - (cd ${TRAVIS_BUILD_DIR}/ext; export CFLAGS="-g0 -O0 -std=gnu90"; phpize &> /dev/null && ./configure --silent --enable-beanspeak &> /dev/null && make --silent -j2 &> /dev/null && make --silent install)
  - phpenv config-add tests/_ci/beanspeack.ini
  - ulimit -c unlimited -S || true
  - echo '/tmp/core_%e.%p' | sudo tee /proc/sys/kernel/core_pattern &> /dev/null
  - stty cols 160

script:
  - php --ri beanspeack

addons:
  apt:
    packages:
      - gdb
      - re2c
