language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

branches:
  except:
    - docs

sudo: required
dist: trusty

env:
  global:
    - TEST_BT_HOST="127.0.0.1"
    - TEST_BT_PORT="11300"

cache:
  - apt

before_install:
  - export PATH=$PATH:~/bin;
  - travis_retry composer self-update
  - sudo service docker stop

  # Install Zephir
  - docker pull phalconphp/zephir
  - cp tests/_ci/zephir.sh /usr/local/bin/zephir
  # Install Beanstalk
  - bash tests/_ci/install_beanstalkd.sh

install:
  # Install Docker
  - sudo apt-get update -qq
  - sudo apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y --force-yes docker-engine
  - sudo service docker restart

before_script:
  # Build extension
  - '[[ "$TRAVIS_PHP_VERSION" == "7" ]] || zephir:$TRAVIS_PHP_VERSION build'
  - '[[ "$TRAVIS_PHP_VERSION" != "7" ]] || zephir:$TRAVIS_PHP_VERSION build --ZendEngine3'

  - echo "extension=${TRAVIS_BUILD_DIR}/ext/modules/beanspeak.so" | tee tests/_ci/beanspeak.ini
  - phpenv config-add tests/_ci/beanspeak.ini
  - ulimit -c unlimited -S || true
  - echo '/tmp/core_%e.%p' | sudo tee /proc/sys/kernel/core_pattern &> /dev/null
  - stty cols 160

script:
  - php --ri beanspeak

addons:
  apt:
    packages:
      - gdb
      - re2c
