language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

branches:
  except:
    - docs

sudo: required
dist: precise
group: edge

env:
  global:
    - TEST_BT_HOST="127.0.0.1"
    - TEST_BT_PORT="11300"

cache:
  - apt

before_install:
  - export PATH=$PATH:~/bin;
  - travis_retry composer self-update
  - travis_retry composer require phalcon/zephir:dev-master
  - bash tests/_ci/install_zephir.sh
  - bash tests/_ci/install_beanstalkd.sh

before_script:
  - '[[ "$TRAVIS_PHP_VERSION" == "7" ]] || zephir build'
  - '[[ "$TRAVIS_PHP_VERSION" != "7" ]] || zephir build --ZendEngine3'
  - echo "extension=${TRAVIS_BUILD_DIR}/ext/modules/beanspeak.so" | tee tests/_ci/beanspeak.ini
  - phpenv config-add tests/_ci/beanspeak.ini
  - ulimit -c unlimited -S || true
  - echo '/tmp/core_%e.%p' | sudo tee /proc/sys/kernel/core_pattern &> /dev/null
  - stty cols 160

script:
  - php --ri beanspeak

addons:
  apt:
    packages:
      - gdb
      - re2c
