#  Beanspeak
#
#  Copyright (c) 2016 Phalcon Team (http://www.phalconphp.com)
#
#  This source file is subject to the New BSD License that is bundled
#  with this package in the file LICENSE.txt.
#
#  If you did not receive a copy of the license and are unable to
#  obtain it through the world-wide-web, please send an email
#  to license@phalconphp.com so we can send you a copy immediately.
#
#  Authors: Serghei Iakovlev <serghei@phalconphp.com>

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

branches:
  except:
    - docs

sudo: required
dist: trusty

cache:
  - apt

before_install:
  - phpenv config-rm xdebug.ini
  - sudo service docker stop

install:
  # Install Docker
  - sudo apt-get update -qq
  - sudo apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y --force-yes docker-engine
  - sudo service docker restart
  # Install Zephir
  - docker pull phalconphp/zephir:$TRAVIS_PHP_VERSION
  - sudo cp tests/_ci/zephir.sh /usr/local/bin/zephir && sudo chmod +x /usr/local/bin/zephir
  # Install PHP
  - docker pull phalconphp/php:$TRAVIS_PHP_VERSION
  - sudo cp tests/_ci/run.sh /usr/local/bin/beanspeak-test && sudo chmod +x /usr/local/bin/beanspeak-test
  # Install Composer
  - docker pull phalconphp/composer:$TRAVIS_PHP_VERSION
  - sudo cp tests/_ci/composer.sh /home/travis/.phpenv/shims/composer && sudo chmod +x /home/travis/.phpenv/shims/composer
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi
  - travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs
  # Setup network
  - docker network create --driver bridge beanstalk_nw
  # Install Beanstalkd
  - docker pull phalconphp/beanstalkd:1.10
  - bash tests/_ci/beanstalkd.sh

before_script:
  # Build extension
  - '[[ "$TRAVIS_PHP_VERSION" == "7.0" ]] || zephir builddev'
  - '[[ "$TRAVIS_PHP_VERSION" != "7.0" ]] || zephir builddev --ZendEngine3'

script:
  # Run tests
  - beanspeak-test
